apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-dashboard
  namespace: cleifsonaraujo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-dashboard
  template:
    metadata:
      labels:
        app: monitoring-dashboard
    spec:
      containers:
      - name: dashboard
        image: cleifson/monitoring-dashboard:01
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-dashboard
spec:
  selector:
    app: monitoring-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort
