apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-cleifsonaraujo-claim
  namespace: cleifsonaraujo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: cleifsonaraujo
  storageClassName: default-storage-class-cleifsonaraujo
